# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Angular App to Azure Web App - ircc-aisearch-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 'Set Environment Variables'
        env:
          EMBEDDING_API_URL: ${{ secrets.EMBEDDING_API_URL }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          SEARCH_API_URL: ${{ secrets.SEARCH_API_URL }}
          SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
          GENERATE_API_URL: ${{ secrets.GENERATE_API_URL }}
          GENERATE_API_KEY: ${{ secrets.GENERATE_API_KEY }}
        run: |
          sed -i "s#embeddingApiUrl: ''#embeddingApiUrl: '$EMBEDDING_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#embeddingApiKey: ''#embeddingApiKey: '$EMBEDDING_API_KEY'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#searchApiUrl: ''#searchApiUrl: '$SEARCH_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#searchApiKey: ''#searchApiKey: '$SEARCH_API_KEY'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#generateSynthesisApiUrl: ''#generateSynthesisApiUrl: '$GENERATE_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#generateSynthesisApiCode: ''#generateSynthesisApiCode: '$GENERATE_API_KEY'#g" ./frontend/src/environments/environment.prod.ts

      - name: npm install, build, and test
        run: |
          cd frontend
          npm install
          npm install -g @angular/cli
          ng build

      - name: Zip artifact for deployment
        run: |
          cd frontend
          zip -r release.zip dist server.js

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ircc-search-frontend-sen'
          package: .
