name: Build and Deploy Angular App to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set Environment Variables
        run: |
          echo "export EMBEDDING_API_URL=${{ secrets.EMBEDDING_API_URL }}" >> $GITHUB_ENV
          echo "export EMBEDDING_API_KEY=${{ secrets.EMBEDDING_API_KEY }}" >> $GITHUB_ENV
          echo "export SEARCH_API_URL=${{ secrets.SEARCH_API_URL }}" >> $GITHUB_ENV
          echo "export SEARCH_API_KEY=${{ secrets.SEARCH_API_KEY }}" >> $GITHUB_ENV
          echo "export GENERATE_API_URL=${{ secrets.GENERATE_API_URL }}" >> $GITHUB_ENV
          echo "export GENERATE_API_KEY=${{ secrets.GENERATE_API_KEY }}" >> $GITHUB_ENV

      - name: Replace Environment Variables in Angular
        run: |
          sed -i "s#embeddingApiUrl: ''#embeddingApiUrl: '$EMBEDDING_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#embeddingApiKey: ''#embeddingApiKey: '$EMBEDDING_API_KEY'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#searchApiUrl: ''#searchApiUrl: '$SEARCH_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#searchApiKey: ''#searchApiKey: '$SEARCH_API_KEY'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#generateSynthesisApiUrl: ''#generateSynthesisApiUrl: '$GENERATE_API_URL'#g" ./frontend/src/environments/environment.prod.ts
          sed -i "s#generateSynthesisApiCode: ''#generateSynthesisApiCode: '$GENERATE_API_KEY'#g" ./frontend/src/environments/environment.prod.ts

      - name: Verify Environment Variables
        run: |
          echo "Embedding API URL: $EMBEDDING_API_URL"
          echo "Search API URL: $SEARCH_API_URL"
          echo "Generate API URL: $GENERATE_API_URL"

      - name: Install Angular Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Angular App
        run: |
          cd frontend
          npm install -g @angular/cli
          ng build --configuration=production

      - name: Move Built App to Root Directory
        run: |
          mv frontend/dist/frontend build

      - name: Install Server Dependencies
        run: |
          npm install

      - name: Package Application for Deployment
        run: |
          zip -r app.zip build server.js package.json package-lock.json

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ircc-frontend'  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_88F230ED2BFA4188B192B772BD630781 }}
          package: './app.zip'
